import "./globals.css";
import clsx from "clsx";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import Script from "next/script";
const roboto = Roboto({
  subsets: ["latin"],
  display: "swap",
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "https://testing-library.com/img/octopus-32x32.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme = null;
  return (
    <html lang="en">
      <body
        className={clsx(roboto.className, theme && `theme-${theme}`)}
        suppressHydrationWarning
      >
        {children}
        <Script src="/js/script.js" />
      </body>
    </html>
  );
}
